modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="millionareshortbread"
version="1.0.0"
displayName="Millionare Shortbread"
logoFile = "icon.png"

authors="highspeedtrain"
description='''Adds Millionare Shortbread to Create'''
issueTrackerURL="https://github.com/highspeedtrain/MillionareShortbread/issues"

[[dependencies.millionareshortbread]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.millionareshortbread]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.createlawandorder]]
    modId="create"
    mandatory=true
    versionRange="[0.5.1.j,)"
    ordering="NONE"
    side="BOTH"